version: '3.7'

services:

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - POSTGRES_DB=postgres
    ports:
        - "54321:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
